services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1363
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: tasktracker-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1363@db:5432/tasktracker
#      - KAFKA_BOOTSTRAP_SERVERS=external-kafka-host:9092
#      - KAFKA_TOPIC=tinode.account-events
#      - KAFKA_GROUP_ID=fastapi-user-sync-consumer
      - KEYCLOAK_SERVER_URL=https://auth.echo-messenger.ru
      - KEYCLOAK_REALM=realm
      - KEYCLOAK_CLIENT_ID=tasktracker
      - KEYCLOAK_CLIENT_SECRET=<secret>
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./docs:/app/docs
      - ./logs:/app/logs
    command: >
      sh -c "echo 'Waiting for services to be ready...' &&
             sleep 25 &&
             echo 'Starting FastAPI...' &&
             uvicorn main:app --host 0.0.0.0 --port 8000"


volumes:
  postgres_data: