{{- if .Values.openbao.enabled }}
---
# Kafka секреты - ОСТАВЛЯЕМ общие пути
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tasktracker.fullname" . }}-kafka-user
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: {{ include "tasktracker.fullname" . }}-kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/user  # ← secret/kafka/user (общий)
        property: username
        optional: true
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/user  # ← secret/kafka/user (общий)
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tasktracker.fullname" . }}-kafka-sasl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: {{ include "tasktracker.fullname" . }}-kafka-sasl
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENABLE
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/sasl  # ← secret/kafka/sasl (общий)
        property: ENABLE
    - secretKey: MECHANISM
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/sasl  # ← secret/kafka/sasl (общий)
        property: MECHANISM

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tasktracker.fullname" . }}-kafka-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: {{ include "tasktracker.fullname" . }}-kafka-tls
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENABLE
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/tls  # ← secret/kafka/tls (общий)
        property: ENABLE
    - secretKey: INSECURE_SKIP_VERIFY
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/tls  # ← secret/kafka/tls (общий)
        property: INSECURE_SKIP_VERIFY

---
# БАЗА ДАННЫХ - только ее меняем на tasktracker-specific
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "tasktracker.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: {{ include "tasktracker.fullname" . }}-database
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.databaseSecretsPath }}  # ← secret/tasktracker/postgres (наш отдельный)
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.openbao.registrySecretsPath }}  # ← registry/tasktracker/ghcr (наш отдельный)
        property: dockerconfigjson

{{- end }}