apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasktracker.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "tasktracker.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP