apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tasktracker.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage | default "5Gi" }}