name: Build and Push Latest Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: echomessenger
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/echomessenger/tasktracker:latest .

      - name: Push Docker image
        run: docker push ghcr.io/echomessenger/tasktracker:latest